name: Checkmarx One Scan
on:
  push:
    branches:
      - main
      - master
      - dev
  #schedule:
  #  - cron: "*/5 * * * *"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@2.0.18 #Github Action version
        with:
          project_name: apcxtest/emptytest
          cx_tenant: dp_wp_account
          base_uri: https://eu.ast.checkmarx.net
          cx_client_id: ${{ secrets.oauthclient }}
          cx_client_secret: ${{ secrets.oauthsecret }}
          additional_params:  --scan-types sast --report-format sarif --output-path .
          #additional_params: --apikey ${{ secrets.apisecret2 }}
          #additional_params: --sast-preset-name "Checkmarx Default" --tags "blueberry"
          #additional_params: --sast-preset-name "Checkmarx Default" --scan-types sast --debug
          #update the yml
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with: 
          sarif_file: cx_result.sarif
